### PR TITLE
SeeSaw(): Some minor changes

### PR DESCRIPTION
**Pull request by Helenerineium**
1. Introduce a relative limiting
2. Simplify the oversampling process

### CODE REVIEW

**Comment by Helenerineium** [comment]
Relative limiting can sometimes be useful IMHO.

Feel free to adjust the naming or other things to the way you like it.

I didn't bother to code the issue opened by me since I feel that it will be more appropriate to let you commit the changes yourself.

**Comment by WolframRhodium** [comment]
Thanks

**Comment by WolframRhodium** [comment]
I've noticed your words in PR #6. Sorry for my childish, I didn't consider how much my response had hurt you. You could reopen that PR and I would accept it ASAP.

**Comment by Helenerineium** [comment]
I edited it a week ago, those are actually puns. [See here](http://www.mediafire.com/folder/33n27d8w8m0u5/Paronomasia) (If you want to know more details, PM me)

I was not very careful when updating the comment, the response didn't hurt me (that much).
Anyway, I am happy you are willing to substitute some removegrain.
I'm not going to reopen that PR, but I might incorporate it with the issue I opened.

**Comment by WolframRhodium** [comment]
I can use Google

**Comment by Helenerineium** [comment]
I think "culture" is not the very best word to describe it, you can click the link and download the files.
They are songs from some music games I played.

**Pull request merged**
